import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Container, Heading, Spinner, Table, Tbody, Td, Th, Thead, Tr } from '@chakra-ui/react'
import { useProducts } from '@/features/product/useProducts'
import { useQuery } from '@tanstack/react-query'
import { axiosInstance } from '@/lib/axios'


export default function Home() {
  const {data, isLoading} = useProducts();


  const renderProducts = () => {
    return data?.data.map((product) => {
      return (
        <Tr key={product.id}>

          <Td>{product.id}</Td>
          <Td>{product.name}</Td>
          <Td>{product.price}</Td>
          <Td>{product.stock}</Td>
          <Td>{product.description}</Td>
          <Td>{product.image}</Td>
        </Tr>
      )
    })
  }


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Heading>Hello World</Heading>
          <Table>
            <Thead>
              <Tr>
                <Th>ID</Th>
                <Th>Name</Th>
                <Th>Price</Th>
                <Th>Stock</Th>
                <Th>Description</Th>
                <Th>Image</Th>
              </Tr>
            </Thead>

            <Tbody>

              {renderProducts()}
              {isLoading && <Spinner />}
            </Tbody>
          </Table>
        </Container>
      </main>
    </>
  )
}
