import Head from "next/head";
import { Inter } from "next/font/google";
import {
  Button,
  Container,
  FormControl,
  FormLabel,
  Heading,
  Input,
  Spinner,
  Table,
  Tbody,
  Td,
  Th,
  Thead,
  Tr,
  VStack,
} from "@chakra-ui/react";
import { useFetchProducts } from "@/features/product/useFetchProducts";
import { useQuery } from "@tanstack/react-query";
import { axiosInstance } from "@/lib/axios";
import { useFormik } from "formik";

export default function Home() {
  const { data, isLoading } = useFetchProducts();

  const formik = useFormik({
    initialValues: {
      name: "",
      price: "",
      stock: "",
      description: "",
      image: "",
    },
  });

  const handleFormInput = (event) => {
    formik.setFieldValue(event.target.name, event.target.value);
  };

  const renderProducts = () => {
    return data?.data.map((product) => {
      return (
        <Tr key={product.id}>
          <Td>{product.id}</Td>
          <Td>{product.name}</Td>
          <Td>{product.price}</Td>
          <Td>{product.stock}</Td>
          <Td>{product.description}</Td>
          <Td>{product.image}</Td>
        </Tr>
      );
    });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Heading>Hello World</Heading>
          <Table mb="6">
            <Thead>
              <Tr>
                <Th>ID</Th>
                <Th>Name</Th>
                <Th>Price</Th>
                <Th>Stock</Th>
                <Th>Description</Th>
                <Th>Image</Th>
              </Tr>
            </Thead>

            <Tbody>
              {renderProducts()}
              {isLoading && <Spinner />}
            </Tbody>
          </Table>
          <text>
            {formik.values.name}
          </text>
          <form>
            <VStack spacing="3">
              <FormControl>
                <FormLabel>Product Name:</FormLabel>
                <Input onChange={handleFormInput} name="name" />
              </FormControl>
              <FormControl>
                <FormLabel>Price:</FormLabel>
                <Input onChange={handleFormInput} name="price" />
              </FormControl>
              <FormControl>
                <FormLabel>Stock:</FormLabel>
                <Input onChange={handleFormInput} name="stock" />
              </FormControl>
              <FormControl>
                <FormLabel>Description:</FormLabel>
                <Input onChange={handleFormInput} name="description" />
              </FormControl>
              <FormControl>
                <FormLabel>Image:</FormLabel>
                <Input onChange={handleFormInput} name="image" />
              </FormControl>
              <Button>Submit Product</Button>
            </VStack>
          </form>
        </Container>
      </main>
    </>
  );
}
